In [1]:
import numpy as np
nov = np.array([[11,13,20,25,6,20,9,20,11,30,8,24,10,27],[9,23,7,27,13,23,15,29,9,29,11,27,7,22],[11,27,13,24,13,22,15,29,13,25,8,23,13,31],[11,24,12,25,9,22,7,21,6,26,14,27,8,30],[8,20,6,22,8,20,8,21,5,20,6,4,20,5],[2,20,2,22,4,19,3,19,2,21,8,2,22,3],[7,18,6,20,6,21,7,19,8,22,3,2,18,4],[7,21,3,19,7,19,6,20,6,20,3,2,18,3],[10,26,11,28,14,31,9,30,11,32,7,21,10,21],[10,28,12,30,12,26,13,24,9,24,8,24,7,23],[7,29,11,32,8,26,10,22,10,29,6,29,12,23],[11,27,10,29,6,32,11,27,9,28,6,23,6,27],[10,20,7,18,10,20,12,22,9,22,12,71,19,9],[9,18,8,18,12,19,9,20,7,18,7,11,22,10],[9,19,10,19,9,22,9,22,7,22,10,8,22,11],[10,22,11,18,8,19,12,22,12,18,11,10,19,12]])
nov

array([[11, 13, 20, 25,  6, 20,  9, 20, 11, 30,  8, 24, 10, 27],
       [ 9, 23,  7, 27, 13, 23, 15, 29,  9, 29, 11, 27,  7, 22],
       [11, 27, 13, 24, 13, 22, 15, 29, 13, 25,  8, 23, 13, 31],
       [11, 24, 12, 25,  9, 22,  7, 21,  6, 26, 14, 27,  8, 30],
       [ 8, 20,  6, 22,  8, 20,  8, 21,  5, 20,  6,  4, 20,  5],
       [ 2, 20,  2, 22,  4, 19,  3, 19,  2, 21,  8,  2, 22,  3],
       [ 7, 18,  6, 20,  6, 21,  7, 19,  8, 22,  3,  2, 18,  4],
       [ 7, 21,  3, 19,  7, 19,  6, 20,  6, 20,  3,  2, 18,  3],
       [10, 26, 11, 28, 14, 31,  9, 30, 11, 32,  7, 21, 10, 21],
       [10, 28, 12, 30, 12, 26, 13, 24,  9, 24,  8, 24,  7, 23],
       [ 7, 29, 11, 32,  8, 26, 10, 22, 10, 29,  6, 29, 12, 23],
       [11, 27, 10, 29,  6, 32, 11, 27,  9, 28,  6, 23,  6, 27],
       [10, 20,  7, 18, 10, 20, 12, 22,  9, 22, 12, 71, 19,  9],
       [ 9, 18,  8, 18, 12, 19,  9, 20,  7, 18,  7, 11, 22, 10],
       [ 9, 19, 10, 19,  9, 22,  9, 22,  7, 22, 10,  8, 22, 11],
       [10, 22, 11, 18,  

In [3]:
newshape = nov.reshape(4,4,7,2)
newshape

array([[[[11, 13],
         [20, 25],
         [ 6, 20],
         [ 9, 20],
         [11, 30],
         [ 8, 24],
         [10, 27]],

        [[ 9, 23],
         [ 7, 27],
         [13, 23],
         [15, 29],
         [ 9, 29],
         [11, 27],
         [ 7, 22]],

        [[11, 27],
         [13, 24],
         [13, 22],
         [15, 29],
         [13, 25],
         [ 8, 23],
         [13, 31]],

        [[11, 24],
         [12, 25],
         [ 9, 22],
         [ 7, 21],
         [ 6, 26],
         [14, 27],
         [ 8, 30]]],


       [[[ 8, 20],
         [ 6, 22],
         [ 8, 20],
         [ 8, 21],
         [ 5, 20],
         [ 6,  4],
         [20,  5]],

        [[ 2, 20],
         [ 2, 22],
         [ 4, 19],
         [ 3, 19],
         [ 2, 21],
         [ 8,  2],
         [22,  3]],

        [[ 7, 18],
         [ 6, 20],
         [ 6, 21],
         [ 7, 19],
         [ 8, 22],
         [ 3,  2],
         [18,  4]],

        [[ 7, 21],
         [ 3, 19],
         [ 7, 1

In [9]:
newshape.ndim


4

In [8]:
newshape.shape

(4, 4, 7, 2)

In [10]:
newshape[0:5,0:1,0:8]

array([[[[11, 13],
         [20, 25],
         [ 6, 20],
         [ 9, 20],
         [11, 30],
         [ 8, 24],
         [10, 27]]],


       [[[ 8, 20],
         [ 6, 22],
         [ 8, 20],
         [ 8, 21],
         [ 5, 20],
         [ 6,  4],
         [20,  5]]],


       [[[10, 26],
         [11, 28],
         [14, 31],
         [ 9, 30],
         [11, 32],
         [ 7, 21],
         [10, 21]]],


       [[[10, 20],
         [ 7, 18],
         [10, 20],
         [12, 22],
         [ 9, 22],
         [12, 71],
         [19,  9]]]])

In [11]:
newshape[0:5,0:5,1:2]

array([[[[20, 25]],

        [[ 7, 27]],

        [[13, 24]],

        [[12, 25]]],


       [[[ 6, 22]],

        [[ 2, 22]],

        [[ 6, 20]],

        [[ 3, 19]]],


       [[[11, 28]],

        [[12, 30]],

        [[11, 32]],

        [[10, 29]]],


       [[[ 7, 18]],

        [[ 8, 18]],

        [[10, 19]],

        [[11, 18]]]])

In [12]:
newshape[1:5:2,0:5,0:8,1:2]

array([[[[20],
         [22],
         [20],
         [21],
         [20],
         [ 4],
         [ 5]],

        [[20],
         [22],
         [19],
         [19],
         [21],
         [ 2],
         [ 3]],

        [[18],
         [20],
         [21],
         [19],
         [22],
         [ 2],
         [ 4]],

        [[21],
         [19],
         [19],
         [20],
         [20],
         [ 2],
         [ 3]]],


       [[[20],
         [18],
         [20],
         [22],
         [22],
         [71],
         [ 9]],

        [[18],
         [18],
         [19],
         [20],
         [18],
         [11],
         [10]],

        [[19],
         [19],
         [22],
         [22],
         [22],
         [ 8],
         [11]],

        [[22],
         [18],
         [19],
         [22],
         [18],
         [10],
         [12]]]])

In [13]:
newshape[1:3]>20

array([[[[False, False],
         [False,  True],
         [False, False],
         [False,  True],
         [False, False],
         [False, False],
         [False, False]],

        [[False, False],
         [False,  True],
         [False, False],
         [False, False],
         [False,  True],
         [False, False],
         [ True, False]],

        [[False, False],
         [False, False],
         [False,  True],
         [False, False],
         [False,  True],
         [False, False],
         [False, False]],

        [[False,  True],
         [False, False],
         [False, False],
         [False, False],
         [False, False],
         [False, False],
         [False, False]]],


       [[[False,  True],
         [False,  True],
         [False,  True],
         [False,  True],
         [False,  True],
         [False,  True],
         [False,  True]],

        [[False,  True],
         [False,  True],
         [False,  True],
         [False,  True],
         [Fal